[package]
name = "smth-integration-tests"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
anyhow.workspace = true
clap.workspace = true
futures.workspace = true
humantime.workspace = true
nonempty.workspace = true
regex.workspace = true
shlex.workspace = true
tempfile.workspace = true
textwrap.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tracing.workspace = true
unicode-width.workspace = true
vt100.workspace = true
which.workspace = true
winnow.workspace = true

[dev-dependencies]
datatest-stable.workspace = true
insta.workspace = true
telemetry-subscribers.workspace = true

[[test]]
name = "test"
path = "tests/test.rs"
harness = false
